const char* RawScenarios[110] = {
	"Standing",
	"WORLD_HUMAN_AA_COFFEE",
	"WORLD_HUMAN_AA_SMOKE",
	"WORLD_HUMAN_BINOCULARS",
	"WORLD_HUMAN_BUM_FREEWAY",
	"WORLD_HUMAN_BUM_SLUMPED",
	"WORLD_HUMAN_BUM_STANDING",
	"WORLD_HUMAN_BUM_WASH",
	"WORLD_HUMAN_CAR_PARK_ATTENDANT",
	"WORLD_HUMAN_CHEERING",
	"WORLD_HUMAN_CLIPBOARD",
	"WORLD_HUMAN_CONST_DRILL",
	"WORLD_HUMAN_COP_IDLES",
	"WORLD_HUMAN_DRINKING",
	"WORLD_HUMAN_DRUG_DEALER",
	"WORLD_HUMAN_DRUG_DEALER_HARD",
	"WORLD_HUMAN_MOBILE_FILM_SHOCKING",
	"WORLD_HUMAN_GARDENER_LEAF_BLOWER",
	"WORLD_HUMAN_GARDENER_PLANT",
	"WORLD_HUMAN_GOLF_PLAYER",
	"WORLD_HUMAN_GUARD_PATROL",
	"WORLD_HUMAN_GUARD_STAND",
	"WORLD_HUMAN_GUARD_STAND_ARMY",
	"WORLD_HUMAN_HAMMERING",
	"WORLD_HUMAN_HANG_OUT_STREET",
	"WORLD_HUMAN_HIKER_STANDING",
	"WORLD_HUMAN_HUMAN_STATUE",
	"WORLD_HUMAN_JANITOR",
	"WORLD_HUMAN_JOG_STANDING",
	"WORLD_HUMAN_LEANING",
	"WORLD_HUMAN_MAID_CLEAN",
	"WORLD_HUMAN_MUSCLE_FLEX",
	"WORLD_HUMAN_MUSCLE_FREE_WEIGHTS",
	"WORLD_HUMAN_MUSICIAN",
	"WORLD_HUMAN_PAPARAZZI",
	"WORLD_HUMAN_PARTYING",
	"WORLD_HUMAN_PICNIC",
	"WORLD_HUMAN_PROSTITUTE_HIGH_CLASS",
	"WORLD_HUMAN_PROSTITUTE_LOW_CLASS",
	"WORLD_HUMAN_PUSH_UPS",
	"WORLD_HUMAN_SEAT_LEDGE",
	"WORLD_HUMAN_SEAT_LEDGE_EATING",
	"WORLD_HUMAN_SEAT_STEPS",
	"WORLD_HUMAN_SEAT_WALL",
	"WORLD_HUMAN_SEAT_WALL_EATING",
	"WORLD_HUMAN_SEAT_WALL_TABLET",
	"WORLD_HUMAN_SECURITY_SHINE_TORCH",
	"WORLD_HUMAN_SIT_UPS",
	"WORLD_HUMAN_SMOKING",
	"WORLD_HUMAN_SMOKING_POT",
	"WORLD_HUMAN_STAND_FIRE",
	"WORLD_HUMAN_STAND_FISHING",
	"WORLD_HUMAN_STAND_IMPATIENT",
	"WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT",
	"WORLD_HUMAN_STAND_MOBILE",
	"WORLD_HUMAN_STAND_MOBILE_UPRIGHT",
	"WORLD_HUMAN_STRIP_WATCH_STAND",
	"WORLD_HUMAN_STUPOR",
	"WORLD_HUMAN_SUNBATHE",
	"WORLD_HUMAN_SUNBATHE_BACK",
	"WORLD_HUMAN_SUPERHERO",
	"WORLD_HUMAN_SWIMMING",
	"WORLD_HUMAN_TENNIS_PLAYER",
	"WORLD_HUMAN_TOURIST_MAP",
	"WORLD_HUMAN_TOURIST_MOBILE",
	"WORLD_HUMAN_VEHICLE_MECHANIC",
	"WORLD_HUMAN_WELDING",
	"WORLD_HUMAN_WINDOW_SHOP_BROWSE",
	"WORLD_HUMAN_YOGA",
	"PROP_HUMAN_ATM",
	"PROP_HUMAN_BBQ",
	"PROP_HUMAN_BUM_BIN",
	"PROP_HUMAN_BUM_SHOPPING_CART",
	"PROP_HUMAN_MUSCLE_CHIN_UPS",
	"PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY",
	"PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON",
	"PROP_HUMAN_PARKING_METER",
	"PROP_HUMAN_SEAT_ARMCHAIR",
	"PROP_HUMAN_SEAT_BAR",
	"PROP_HUMAN_SEAT_BENCH",
	"PROP_HUMAN_SEAT_BENCH_DRINK",
	"PROP_HUMAN_SEAT_BENCH_DRINK_BEER",
	"PROP_HUMAN_SEAT_BENCH_FOOD",
	"PROP_HUMAN_SEAT_BUS_STOP_WAIT",
	"PROP_HUMAN_SEAT_CHAIR",
	"PROP_HUMAN_SEAT_CHAIR_DRINK",
	"PROP_HUMAN_SEAT_CHAIR_DRINK_BEER",
	"PROP_HUMAN_SEAT_CHAIR_FOOD",
	"PROP_HUMAN_SEAT_CHAIR_UPRIGHT",
	"PROP_HUMAN_SEAT_CHAIR_MP_PLAYER",
	"PROP_HUMAN_SEAT_COMPUTER",
	"PROP_HUMAN_SEAT_DECKCHAIR",
	"PROP_HUMAN_SEAT_DECKCHAIR_DRINK",
	"PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS",
	"PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON",
	"PROP_HUMAN_SEAT_SEWING",
	"PROP_HUMAN_SEAT_STRIP_WATCH",
	"PROP_HUMAN_SEAT_SUNLOUNGER",
	"PROP_HUMAN_STAND_IMPATIENT",
	"CODE_HUMAN_COWER",
	"CODE_HUMAN_CROSS_ROAD_WAIT",
	"CODE_HUMAN_PARK_CAR",
	"PROP_HUMAN_MOVIE_BULB",
	"PROP_HUMAN_MOVIE_STUDIO_LIGHT",
	"CODE_HUMAN_MEDIC_KNEEL",
	"CODE_HUMAN_MEDIC_TEND_TO_DEAD",
	"CODE_HUMAN_MEDIC_TIME_OF_DEATH",
	"CODE_HUMAN_POLICE_CROWD_CONTROL",
	"CODE_HUMAN_POLICE_INVESTIGATE",
	"CODE_HUMAN_STAND_COWER",
};
const char* Scenarios[110] = {
	"Standing",
	"Aa coffee",
	"Aa smoke",
	"Binoculars",
	"Bum freeway",
	"Bum slumped",
	"Bum standing",
	"Bum wash",
	"Car park attendant",
	"Cheering",
	"Clipboard",
	"Const drill",
	"Cop idles",
	"Drinking",
	"Drug dealer",
	"Drug dealer hard",
	"Mobile film shocking",
	"Gardener leaf blower",
	"Gardener plant",
	"Golf player",
	"Guard patrol",
	"Guard stand",
	"Guard stand army",
	"Hammering",
	"Hang out street",
	"Hiker standing",
	"Human statue",
	"Janitor",
	"Jog standing",
	"Leaning",
	"Maid clean",
	"Muscle flex",
	"Muscle free weights",
	"Musician",
	"Paparazzi",
	"Partying",
	"Picnic",
	"Prostitute high class",
	"Prostitute low class",
	"Push ups",
	"Seat ledge",
	"Seat ledge eating",
	"Seat steps",
	"Seat wall",
	"Seat wall eating",
	"Seat wall tablet",
	"Security shine torch",
	"Sit ups",
	"Smoking",
	"Smoking pot",
	"Stand fire",
	"Stand fishing",
	"Stand impatient",
	"Stand impatient upright",
	"Stand mobile",
	"Stand mobile upright",
	"Strip watch stand",
	"Stupor",
	"Sunbathe",
	"Sunbathe back",
	"Superhero",
	"Swimming",
	"Tennis player",
	"Tourist map",
	"Tourist mobile",
	"Vehicle mechanic",
	"Welding",
	"Window shop browse",
	"Yoga",
	"Atm",
	"Bbq",
	"Bum bin",
	"Bum shopping cart",
	"Muscle chin ups",
	"Muscle chin ups army",
	"Muscle chin ups prison",
	"Parking meter",
	"Seat armchair",
	"Seat bar",
	"Seat bench",
	"Seat bench drink",
	"Seat bench drink beer",
	"Seat bench food",
	"Seat bus stop wait",
	"Seat chair",
	"Seat chair drink",
	"Seat chair drink beer",
	"Seat chair food",
	"Seat chair upright",
	"Seat chair mp player",
	"Seat computer",
	"Seat deckchair",
	"Seat deckchair drink",
	"Seat muscle bench press",
	"Seat muscle bench press prison",
	"Seat sewing",
	"Seat strip watch",
	"Seat sunlounger",
	"Stand impatient",
	"Cower",
	"Cross road wait",
	"Park car",
	"Movie bulb",
	"Movie studio light",
	"Medic kneel",
	"Medic tend to dead",
	"Medic time of death",
	"Police crowd control",
	"Police investigate",
	"Stand cower",
};

const char* MovementsRaw[82] = {
	"move_m@wading",
	"move_m@tool_belt@a",
	"move_m@shy@e",
	"move_m@shy@d",
	"move_m@shy@c",
	"move_m@shy@b",
	"move_m@shy@a",
	"move_m@shocked@a",
	"move_m@shadyped@a",
	"move_m@scared@a",
	"move_m@sad@c",
	"move_m@sad@b",
	"move_m@sad@a",
	"move_m@quick",
	"move_m@powerwalk",
	"move_m@muscle@a",
	"move_m@multiplayer",
	"move_m@melee",
	"move_m@leaf_blower",
	"move_m@joy@a",
	"move_m@jogger",
	"move_m@jog@",
	"move_m@janitor",
	"move_m@intimidation@unarmed",
	"move_m@intimidation@idle_a",
	"move_m@intimidation@cop@unarmed",
	"move_m@intimidation@1h",
	"move_m@injured",
	"move_m@hurry_butch@c",
	"move_m@hurry_butch@b",
	"move_m@hurry_butch@a",
	"move_m@hurry@c",
	"move_m@hurry@b",
	"move_m@hurry@a",
	"move_m@hobo@b",
	"move_m@hobo@a",
	"move_m@hipster@a",
	"move_m@hiking",
	"move_m@golfer@",
	"move_m@generic_variations@walk",
	"move_m@generic_variations@run",
	"move_m@generic_variations@idle@b",
	"move_m@generic_variations@idle@a",
	"move_m@generic_idles@std",
	"move_m@generic",
	"move_m@gangster@generic",
	"move_m@gangster@a",
	"move_m@flee@c",
	"move_m@flee@b",
	"move_m@flee@a",
	"move_m@fire",
	"move_m@fat@a",
	"move_m@drunk@verydrunk",
	"move_m@drunk@transitions",
	"move_m@drunk@slightlydrunk",
	"move_m@drunk@moderatedrunk_head_up",
	"move_m@drunk@moderatedrunk",
	"move_m@drunk@a",
	"move_m@depressed@a",
	"move_m@coward",
	"move_m@copchase2",
	"move_m@copchase1",
	"move_m@clipboard",
	"move_m@chubby@a",
	"move_m@casual@f",
	"move_m@casual@e",
	"move_m@casual@d",
	"move_m@casual@c",
	"move_m@casual@b",
	"move_m@casual@a",
	"move_m@business@c",
	"move_m@business@b",
	"move_m@business@a",
	"move_m@breathe",
	"move_m@brave@idle_b",
	"move_m@brave@idle_a",
	"move_m@brave@fallback",
	"move_m@brave@b",
	"move_m@brave@a",
	"move_m@brave",
	"move_m@bail_bond",
	"move_m@alien",
};

const char* Movements[82] = {
	"Wading",
	"Tool belt a",
	"Shy e",
	"Shy d",
	"Shy c",
	"Shy b",
	"Shy a",
	"Shocked a",
	"Shadyped a",
	"Scared a",
	"Sad c",
	"Sad b",
	"Sad a",
	"Quick",
	"Powerwalk",
	"Muscle a",
	"Multiplayer",
	"Melee",
	"Leaf blower",
	"Joy a",
	"Jogger",
	"Jog ",
	"Janitor",
	"Intimidation unarmed",
	"Intimidation idle a",
	"Intimidation cop unarmed",
	"Intimidation 1h",
	"Injured",
	"Hurry butch c",
	"Hurry butch b",
	"Hurry butch a",
	"Hurry c",
	"Hurry b",
	"Hurry a",
	"Hobo b",
	"Hobo a",
	"Hipster a",
	"Hiking",
	"Golfer ",
	"Generic variations walk",
	"Generic variations run",
	"Generic variations idle b",
	"Generic variations idle a",
	"Generic idles std",
	"Generic",
	"Gangster generic",
	"Gangster a",
	"Flee c",
	"Flee b",
	"Flee a",
	"Fire",
	"Fat a",
	"Drunk verydrunk",
	"Drunk transitions",
	"Drunk slightlydrunk",
	"Drunk moderatedrunk head up",
	"Drunk moderatedrunk",
	"Drunk a",
	"Depressed a",
	"Coward",
	"Copchase2",
	"Copchase1",
	"Clipboard",
	"Chubby a",
	"Casual f",
	"Casual e",
	"Casual d",
	"Casual c",
	"Casual b",
	"Casual a",
	"Business c",
	"Business b",
	"Business a",
	"Breathe",
	"Brave idle b",
	"Brave idle a",
	"Brave fallback",
	"Brave b",
	"Brave a",
	"Brave",
	"Bail bond",
	"Alien",
};