const char *AmbientFemales[69] = {
	"a_f_m_beach_01",
	"a_f_m_bevhills_01",
	"a_f_m_bevhills_02",
	"a_f_m_bodybuild_01",
	"a_f_m_business_02",
	"a_f_m_downtown_01",
	"a_f_m_eastsa_01",
	"a_f_m_eastsa_02",
	"a_f_m_fatbla_01",
	"a_f_m_fatcult_01",
	"a_f_m_fatwhite_01",
	"a_f_m_ktown_01",
	"a_f_m_ktown_02",
	"a_f_m_prolhost_01",
	"a_f_m_salton_01",
	"a_f_m_skidrow_01",
	"a_f_m_soucentmc_01",
	"a_f_m_soucent_01",
	"a_f_m_soucent_02",
	"a_f_m_tourist_01",
	"a_f_m_trampbeac_01",
	"a_f_m_tramp_01",
	"a_f_o_genstreet_01",
	"a_f_o_indian_01",
	"a_f_o_ktown_01",
	"a_f_o_salton_01",
	"a_f_o_soucent_01",
	"a_f_o_soucent_02",
	"a_f_y_beach_01",
	"a_f_y_bevhills_01",
	"a_f_y_bevhills_02",
	"a_f_y_bevhills_03",
	"a_f_y_bevhills_04",
	"a_f_y_business_01",
	"a_f_y_business_02",
	"a_f_y_business_03",
	"a_f_y_business_04",
	"a_f_y_eastsa_01",
	"a_f_y_eastsa_02",
	"a_f_y_eastsa_03",
	"a_f_y_epsilon_01",
	"a_f_y_fitness_01",
	"a_f_y_fitness_02",
	"a_f_y_genhot_01",
	"a_f_y_golfer_01",
	"a_f_y_hiker_01",
	"a_f_y_hippie_01",
	"a_f_y_hipster_01",
	"a_f_y_hipster_02",
	"a_f_y_hipster_03",
	"a_f_y_hipster_04",
	"a_f_y_indian_01",
	"a_f_y_juggalo_01",
	"a_f_y_runner_01",
	"a_f_y_rurmeth_01",
	"a_f_y_scdressy_01",
	"a_f_y_skater_01",
	"a_f_y_soucent_01",
	"a_f_y_soucent_02",
	"a_f_y_soucent_03",
	"a_f_y_tennis_01",
	"a_f_y_topless_01",
	"a_f_y_tourist_01",
	"a_f_y_tourist_02",
	"a_f_y_vinewood_01",
	"a_f_y_vinewood_02",
	"a_f_y_vinewood_03",
	"a_f_y_vinewood_04",
	"a_f_y_yoga_01",
};
const char *AmbientFemalesDisplay[69] = {
	"Beach 01",
	"Bevhills 01",
	"Bevhills 02",
	"Bodybuild 01",
	"Business 02",
	"Downtown 01",
	"Eastsa 01",
	"Eastsa 02",
	"Fatbla 01",
	"Fatcult 01",
	"Fatwhite 01",
	"Ktown 01",
	"Ktown 02",
	"Prolhost 01",
	"Salton 01",
	"Skidrow 01",
	"Soucentmc 01",
	"Soucent 01",
	"Soucent 02",
	"Tourist 01",
	"Trampbeac 01",
	"Tramp 01",
	"Genstreet 01",
	"Indian 01",
	"Ktown 01",
	"Salton 01",
	"Soucent 01",
	"Soucent 02",
	"Beach 01",
	"Bevhills 01",
	"Bevhills 02",
	"Bevhills 03",
	"Bevhills 04",
	"Business 01",
	"Business 02",
	"Business 03",
	"Business 04",
	"Eastsa 01",
	"Eastsa 02",
	"Eastsa 03",
	"Epsilon 01",
	"Fitness 01",
	"Fitness 02",
	"Genhot 01",
	"Golfer 01",
	"Hiker 01",
	"Hippie 01",
	"Hipster 01",
	"Hipster 02",
	"Hipster 03",
	"Hipster 04",
	"Indian 01",
	"Juggalo 01",
	"Runner 01",
	"Rurmeth 01",
	"Scdressy 01",
	"Skater 01",
	"Soucent 01",
	"Soucent 02",
	"Soucent 03",
	"Tennis 01",
	"Topless 01",
	"Tourist 01",
	"Tourist 02",
	"Vinewood 01",
	"Vinewood 02",
	"Vinewood 03",
	"Vinewood 04",
	"Yoga 01",
};
const char *AmbientMale[168] = {
	"a_m_m_acult_01",
	"a_m_m_afriamer_01",
	"a_m_m_beach_01",
	"a_m_m_beach_02",
	"a_m_m_bevhills_01",
	"a_m_m_bevhills_02",
	"a_m_m_business_01",
	"a_m_m_eastsa_01",
	"a_m_m_eastsa_02",
	"a_m_m_farmer_01",
	"a_m_m_fatlatin_01",
	"a_m_m_genfat_01",
	"a_m_m_genfat_02",
	"a_m_m_golfer_01",
	"a_m_m_hasjew_01",
	"a_m_m_hillbilly_01",
	"a_m_m_hillbilly_02",
	"a_m_m_indian_01",
	"a_m_m_ktown_01",
	"a_m_m_malibu_01",
	"a_m_m_mexcntry_01",
	"a_m_m_mexlabor_01",
	"a_m_m_og_boss_01",
	"a_m_m_paparazzi_01",
	"a_m_m_polynesian_01",
	"a_m_m_prolhost_01",
	"a_m_m_rurmeth_01",
	"a_m_m_salton_01",
	"a_m_m_salton_02",
	"a_m_m_salton_03",
	"a_m_m_salton_04",
	"a_m_m_skater_01",
	"a_m_m_skidrow_01",
	"a_m_m_socenlat_01",
	"a_m_m_soucent_01",
	"a_m_m_soucent_02",
	"a_m_m_soucent_03",
	"a_m_m_soucent_04",
	"a_m_m_stlat_02",
	"a_m_m_tennis_01",
	"a_m_m_tourist_01",
	"a_m_m_trampbeac_01",
	"a_m_m_tramp_01",
	"a_m_m_tranvest_01",
	"a_m_m_tranvest_02",
	"a_m_o_acult_01",
	"a_m_o_acult_02",
	"a_m_o_beach_01",
	"a_m_o_genstreet_01",
	"a_m_o_ktown_01",
	"a_m_o_salton_01",
	"a_m_o_soucent_01",
	"a_m_o_soucent_02",
	"a_m_o_soucent_03",
	"a_m_o_tramp_01",
	"a_m_m_acult_01",
	"a_m_m_afriamer_01",
	"a_m_m_beach_01",
	"a_m_m_beach_02",
	"a_m_m_bevhills_01",
	"a_m_m_bevhills_02",
	"a_m_m_business_01",
	"a_m_m_eastsa_01",
	"a_m_m_eastsa_02",
	"a_m_m_farmer_01",
	"a_m_m_fatlatin_01",
	"a_m_m_genfat_01",
	"a_m_m_genfat_02",
	"a_m_m_golfer_01",
	"a_m_m_hasjew_01",
	"a_m_m_hillbilly_01",
	"a_m_m_hillbilly_02",
	"a_m_m_indian_01",
	"a_m_m_ktown_01",
	"a_m_m_malibu_01",
	"a_m_m_mexcntry_01",
	"a_m_m_mexlabor_01",
	"a_m_m_og_boss_01",
	"a_m_m_paparazzi_01",
	"a_m_m_polynesian_01",
	"a_m_m_prolhost_01",
	"a_m_m_rurmeth_01",
	"a_m_m_salton_01",
	"a_m_m_salton_02",
	"a_m_m_salton_03",
	"a_m_m_salton_04",
	"a_m_m_skater_01",
	"a_m_m_skidrow_01",
	"a_m_m_socenlat_01",
	"a_m_m_soucent_01",
	"a_m_m_soucent_02",
	"a_m_m_soucent_03",
	"a_m_m_soucent_04",
	"a_m_m_stlat_02",
	"a_m_m_tennis_01",
	"a_m_m_tourist_01",
	"a_m_m_trampbeac_01",
	"a_m_m_tramp_01",
	"a_m_m_tranvest_01",
	"a_m_m_tranvest_02",
	"a_m_y_acult_01",
	"a_m_y_acult_02",
	"a_m_y_beachvesp_01",
	"a_m_y_beachvesp_02",
	"a_m_y_beach_01",
	"a_m_y_beach_02",
	"a_m_y_beach_03",
	"a_m_y_bevhills_01",
	"a_m_y_bevhills_02",
	"a_m_y_breakdance_01",
	"a_m_y_busicas_01",
	"a_m_y_business_01",
	"a_m_y_business_02",
	"a_m_y_business_03",
	"a_m_y_cyclist_01",
	"a_m_y_dhill_01",
	"a_m_y_downtown_01",
	"a_m_y_eastsa_01",
	"a_m_y_eastsa_02",
	"a_m_y_epsilon_01",
	"a_m_y_epsilon_02",
	"a_m_y_gay_01",
	"a_m_y_gay_02",
	"a_m_y_genstreet_01",
	"a_m_y_genstreet_02",
	"a_m_y_golfer_01",
	"a_m_y_hasjew_01",
	"a_m_y_hiker_01",
	"a_m_y_hippy_01",
	"a_m_y_hipster_01",
	"a_m_y_hipster_02",
	"a_m_y_hipster_03",
	"a_m_y_indian_01",
	"a_m_y_jetski_01",
	"a_m_y_juggalo_01",
	"a_m_y_ktown_01",
	"a_m_y_ktown_02",
	"a_m_y_latino_01",
	"a_m_y_methhead_01",
	"a_m_y_mexthug_01",
	"a_m_y_motox_01",
	"a_m_y_motox_02",
	"a_m_y_musclbeac_01",
	"a_m_y_musclbeac_02",
	"a_m_y_polynesian_01",
	"a_m_y_roadcyc_01",
	"a_m_y_runner_01",
	"a_m_y_runner_02",
	"a_m_y_salton_01",
	"a_m_y_skater_01",
	"a_m_y_skater_02",
	"a_m_y_soucent_01",
	"a_m_y_soucent_02",
	"a_m_y_soucent_03",
	"a_m_y_soucent_04",
	"a_m_y_stbla_01",
	"a_m_y_stbla_02",
	"a_m_y_stlat_01",
	"a_m_y_stwhi_01",
	"a_m_y_stwhi_02",
	"a_m_y_sunbathe_01",
	"a_m_y_surfer_01",
	"a_m_y_vindouche_01",
	"a_m_y_vinewood_01",
	"a_m_y_vinewood_02",
	"a_m_y_vinewood_03",
	"a_m_y_vinewood_04",
	"a_m_y_yoga_01",
};
const char *AmbientMaleDisplay[168] = {
	"Acult 01",
	"Afriamer 01",
	"Beach 01",
	"Beach 02",
	"Bevhills 01",
	"Bevhills 02",
	"Business 01",
	"Eastsa 01",
	"Eastsa 02",
	"Farmer 01",
	"Fatlatin 01",
	"Genfat 01",
	"Genfat 02",
	"Golfer 01",
	"Hasjew 01",
	"Hillbilly 01",
	"Hillbilly 02",
	"Indian 01",
	"Ktown 01",
	"Malibu 01",
	"Mexcntry 01",
	"Mexlabor 01",
	"Og boss 01",
	"Paparazzi 01",
	"Polynesian 01",
	"Prolhost 01",
	"Rurmeth 01",
	"Salton 01",
	"Salton 02",
	"Salton 03",
	"Salton 04",
	"Skater 01",
	"Skidrow 01",
	"Socenlat 01",
	"Soucent 01",
	"Soucent 02",
	"Soucent 03",
	"Soucent 04",
	"Stlat 02",
	"Tennis 01",
	"Tourist 01",
	"Trampbeac 01",
	"Tramp 01",
	"Tranvest 01",
	"Tranvest 02",
	"Acult 01",
	"Acult 02",
	"Beach 01",
	"Genstreet 01",
	"Ktown 01",
	"Salton 01",
	"Soucent 01",
	"Soucent 02",
	"Soucent 03",
	"Tramp 01",
	"Acult 01",
	"Afriamer 01",
	"Beach 01",
	"Beach 02",
	"Bevhills 01",
	"Bevhills 02",
	"Business 01",
	"Eastsa 01",
	"Eastsa 02",
	"Farmer 01",
	"Fatlatin 01",
	"Genfat 01",
	"Genfat 02",
	"Golfer 01",
	"Hasjew 01",
	"Hillbilly 01",
	"Hillbilly 02",
	"Indian 01",
	"Ktown 01",
	"Malibu 01",
	"Mexcntry 01",
	"Mexlabor 01",
	"Og boss 01",
	"Paparazzi 01",
	"Polynesian 01",
	"Prolhost 01",
	"Rurmeth 01",
	"Salton 01",
	"Salton 02",
	"Salton 03",
	"Salton 04",
	"Skater 01",
	"Skidrow 01",
	"Socenlat 01",
	"Soucent 01",
	"Soucent 02",
	"Soucent 03",
	"Soucent 04",
	"Stlat 02",
	"Tennis 01",
	"Tourist 01",
	"Trampbeac 01",
	"Tramp 01",
	"Tranvest 01",
	"Tranvest 02",
	"Acult 01",
	"Acult 02",
	"Beachvesp 01",
	"Beachvesp 02",
	"Beach 01",
	"Beach 02",
	"Beach 03",
	"Bevhills 01",
	"Bevhills 02",
	"Breakdance 01",
	"Busicas 01",
	"Business 01",
	"Business 02",
	"Business 03",
	"Cyclist 01",
	"Dhill 01",
	"Downtown 01",
	"Eastsa 01",
	"Eastsa 02",
	"Epsilon 01",
	"Epsilon 02",
	"Gay 01",
	"Gay 02",
	"Genstreet 01",
	"Genstreet 02",
	"Golfer 01",
	"Hasjew 01",
	"Hiker 01",
	"Hippy 01",
	"Hipster 01",
	"Hipster 02",
	"Hipster 03",
	"Indian 01",
	"Jetski 01",
	"Juggalo 01",
	"Ktown 01",
	"Ktown 02",
	"Latino 01",
	"Methhead 01",
	"Mexthug 01",
	"Motox 01",
	"Motox 02",
	"Musclbeac 01",
	"Musclbeac 02",
	"Polynesian 01",
	"Roadcyc 01",
	"Runner 01",
	"Runner 02",
	"Salton 01",
	"Skater 01",
	"Skater 02",
	"Soucent 01",
	"Soucent 02",
	"Soucent 03",
	"Soucent 04",
	"Stbla 01",
	"Stbla 02",
	"Stlat 01",
	"Stwhi 01",
	"Stwhi 02",
	"Sunbathe 01",
	"Surfer 01",
	"Vindouche 01",
	"Vinewood 01",
	"Vinewood 02",
	"Vinewood 03",
	"Vinewood 04",
	"Yoga 01",
};
const char *Animals[22] = {
	"a_c_boar",
	"a_c_chickenhawk",
	"a_c_chimp",
	"a_c_cormorant",
	"a_c_cow",
	"a_c_coyote",
	"a_c_crow",
	"a_c_deer",
	"a_c_fish",
	"a_c_hen",
	"a_c_pig",
	"a_c_pigeon",
	"a_c_rat",
	"a_c_rhesus",
	"a_c_seagull",
	"a_c_chop",
	"a_c_husky",
	"a_c_mtlion",
	"a_c_retriever",
	"a_c_rottweiler",
	"a_c_sharktiger",
	"a_c_shepherd",
};
const char *AnimalsDisplay[22] = {
	"Boar",
	"Chickenhawk",
	"Chimp",
	"Cormorant",
	"Cow",
	"Coyote",
	"Crow",
	"Deer",
	"Fish",
	"Hen",
	"Pig",
	"Pigeon",
	"Rat",
	"Rhesus",
	"Seagull",
	"Chop",
	"Husky",
	"Mtlion",
	"Retriever",
	"Rottweiler",
	"Sharktiger",
	"Shepherd",
};
const char *Cutscene[41] = {
	"csb_abigail",
	"csb_anita",
	"csb_anton",
	"csb_ballasog",
	"csb_bride",
	"csb_burgerdrug",
	"csb_car3guy1",
	"csb_car3guy2",
	"csb_chef",
	"csb_chin_goon",
	"csb_cletus",
	"csb_cop",
	"csb_customer",
	"csb_denise_friend",
	"csb_fos_rep",
	"csb_g",
	"csb_groom",
	"csb_grove_str_dlr",
	"csb_hao",
	"csb_hugh",
	"csb_imran",
	"csb_janitor",
	"csb_maude",
	"csb_mweather",
	"csb_ortega",
	"csb_oscar",
	"csb_porndudes",
	"csb_prologuedriver",
	"csb_prolsec",
	"csb_ramp_gang",
	"csb_ramp_hic",
	"csb_ramp_hipster",
	"csb_ramp_marine",
	"csb_ramp_mex",
	"csb_reporter",
	"csb_roccopelosi",
	"csb_screen_writer",
	"csb_stripper_01",
	"csb_stripper_02",
	"csb_tonya",
	"csb_trafficwarden",
};
const char *CutsceneDisplay[41] = {
	"Abigail",
	"Anita",
	"Anton",
	"Ballasog",
	"Bride",
	"Burgerdrug",
	"Car3guy1",
	"Car3guy2",
	"Chef",
	"Chin goon",
	"Cletus",
	"Cop",
	"Customer",
	"Denise friend",
	"Fos rep",
	"G",
	"Groom",
	"Grove str dlr",
	"Hao",
	"Hugh",
	"Imran",
	"Janitor",
	"Maude",
	"Mweather",
	"Ortega",
	"Oscar",
	"Porndudes",
	"Prologuedriver",
	"Prolsec",
	"Ramp gang",
	"Ramp hic",
	"Ramp hipster",
	"Ramp marine",
	"Ramp mex",
	"Reporter",
	"Roccopelosi",
	"Screen writer",
	"Stripper 01",
	"Stripper 02",
	"Tonya",
	"Trafficwarden",
};

const char *GangFemaleDisplay[4] = {
	"Ballas 01",
	"Families 01",
	"Lost 01",
	"Vagos 01",
};
const char *GangFemale[4] = {
	"g_f_y_ballas_01",
	"g_f_y_families_01",
	"g_f_y_lost_01",
	"g_f_y_vagos_01",
};
const char *GangMale[37] = {
	"g_m_m_armboss_01",
	"g_m_m_armgoon_01",
	"g_m_m_armlieut_01",
	"g_m_m_chemwork_01",
	"g_m_m_chiboss_01",
	"g_m_m_chicold_01",
	"g_m_m_chigoon_01",
	"g_m_m_chigoon_02",
	"g_m_m_korboss_01",
	"g_m_m_mexboss_01",
	"g_m_m_mexboss_02",
	"g_m_y_armgoon_02",
	"g_m_y_azteca_01",
	"g_m_y_ballaeast_01",
	"g_m_y_ballaorig_01",
	"g_m_y_ballasout_01",
	"g_m_y_famca_01",
	"g_m_y_famdnf_01",
	"g_m_y_famfor_01",
	"g_m_y_korean_01",
	"g_m_y_korean_02",
	"g_m_y_korlieut_01",
	"g_m_y_lost_01",
	"g_m_y_lost_02",
	"g_m_y_lost_03",
	"g_m_y_mexgang_01",
	"g_m_y_mexgoon_01",
	"g_m_y_mexgoon_02",
	"g_m_y_mexgoon_03",
	"g_m_y_pologoon_01",
	"g_m_y_pologoon_02",
	"g_m_y_salvaboss_01",
	"g_m_y_salvagoon_01",
	"g_m_y_salvagoon_02",
	"g_m_y_salvagoon_03",
	"g_m_y_strpunk_01",
	"g_m_y_strpunk_02",
};
const char *GangMaleDisplay[37] = {
	"Armboss 01",
	"Armgoon 01",
	"Armlieut 01",
	"Chemwork 01",
	"Chiboss 01",
	"Chicold 01",
	"Chigoon 01",
	"Chigoon 02",
	"Korboss 01",
	"Mexboss 01",
	"Mexboss 02",
	"Armgoon 02",
	"Azteca 01",
	"Ballaeast 01",
	"Ballaorig 01",
	"Ballasout 01",
	"Famca 01",
	"Famdnf 01",
	"Famfor 01",
	"Korean 01",
	"Korean 02",
	"Korlieut 01",
	"Lost 01",
	"Lost 02",
	"Lost 03",
	"Mexgang 01",
	"Mexgoon 01",
	"Mexgoon 02",
	"Mexgoon 03",
	"Pologoon 01",
	"Pologoon 02",
	"Salvaboss 01",
	"Salvagoon 01",
	"Salvagoon 02",
	"Salvagoon 03",
	"Strpunk 01",
	"Strpunk 02",
};
const char *Story[96] = {
	"ig_abigail",
	"ig_ashley",
	"ig_bankman",
	"ig_barry",
	"ig_bestmen",
	"ig_beverly",
	"ig_bride",
	"ig_car3guy1",
	"ig_car3guy2",
	"ig_casey",
	"ig_chef",
	"ig_chengsr",
	"ig_chrisformage",
	"ig_clay",
	"ig_claypain",
	"ig_cletus",
	"ig_dale",
	"ig_dreyfuss",
	"ig_fbisuit_01",
	"ig_groom",
	"ig_hao",
	"ig_hunter",
	"ig_janet",
	"ig_jewelass",
	"ig_jimmyboston",
	"ig_joeminuteman",
	"ig_johnnyklebitz",
	"ig_josef",
	"ig_josh",
	"ig_kerrymcintosh",
	"ig_lifeinvad_01",
	"ig_lifeinvad_02",
	"ig_magenta",
	"ig_manuel",
	"ig_marnie",
	"ig_maryann",
	"ig_maude",
	"ig_michelle",
	"ig_mrsphillips",
	"ig_mrs_thornhill",
	"ig_natalia",
	"ig_nigel",
	"ig_old_man1a",
	"ig_old_man2",
	"ig_oneil",
	"ig_ortega",
	"ig_paper",
	"ig_priest",
	"ig_prolsec_02",
	"ig_ramp_gang",
	"ig_ramp_hic",
	"ig_ramp_hipster",
	"ig_ramp_mex",
	"ig_roccopelosi",
	"ig_russiandrunk",
	"ig_screen_writer",
	"ig_talina",
	"ig_tanisha",
	"ig_terry",
	"ig_tomepsilon",
	"ig_tonya",
	"ig_trafficwarden",
	"ig_tylerdix",
	"ig_zimbor",
	"ig_amandatownley",
	"ig_andreas",
	"ig_ballasog",
	"ig_brad",
	"ig_davenorton",
	"ig_denise",
	"ig_devin",
	"ig_dom",
	"ig_drfriedlander",
	"ig_fabien",
	"ig_floyd",
	"ig_jay_norris",
	"ig_jimmydisanto",
	"ig_lamardavis",
	"ig_lazlow",
	"ig_lestercrest",
	"ig_milton",
	"ig_molly",
	"ig_mrk",
	"ig_nervousron",
	"ig_omega",
	"ig_orleans",
	"ig_patricia",
	"ig_siemonyetarian",
	"ig_solomon",
	"ig_stevehains",
	"ig_stretch",
	"ig_taocheng",
	"ig_taostranslator",
	"ig_tenniscoach",
	"ig_tracydisanto",
	"ig_wade",
};
const char *StoryDisplay[96] = {
	"Abigail",
	"Ashley",
	"Bankman",
	"Barry",
	"Bestmen",
	"Beverly",
	"Bride",
	"Car3guy1",
	"Car3guy2",
	"Casey",
	"Chef",
	"Chengsr",
	"Chrisformage",
	"Clay",
	"Claypain",
	"Cletus",
	"Dale",
	"Dreyfuss",
	"Fbisuit 01",
	"Groom",
	"Hao",
	"Hunter",
	"Janet",
	"Jewelass",
	"Jimmyboston",
	"Joeminuteman",
	"Johnnyklebitz",
	"Josef",
	"Josh",
	"Kerrymcintosh",
	"Lifeinvad 01",
	"Lifeinvad 02",
	"Magenta",
	"Manuel",
	"Marnie",
	"Maryann",
	"Maude",
	"Michelle",
	"Mrsphillips",
	"Mrs thornhill",
	"Natalia",
	"Nigel",
	"Old man1a",
	"Old man2",
	"Oneil",
	"Ortega",
	"Paper",
	"Priest",
	"Prolsec 02",
	"Ramp gang",
	"Ramp hic",
	"Ramp hipster",
	"Ramp mex",
	"Roccopelosi",
	"Russiandrunk",
	"Screen writer",
	"Talina",
	"Tanisha",
	"Terry",
	"Tomepsilon",
	"Tonya",
	"Trafficwarden",
	"Tylerdix",
	"Zimbor",
	"Amandatownley",
	"Andreas",
	"Ballasog",
	"Brad",
	"Davenorton",
	"Denise",
	"Devin",
	"Dom",
	"Drfriedlander",
	"Fabien",
	"Floyd",
	"Jay norris",
	"Jimmydisanto",
	"Lamardavis",
	"Lazlow",
	"Lestercrest",
	"Milton",
	"Molly",
	"Mrk",
	"Nervousron",
	"Omega",
	"Orleans",
	"Patricia",
	"Siemonyetarian",
	"Solomon",
	"Stevehains",
	"Stretch",
	"Taocheng",
	"Taostranslator",
	"Tenniscoach",
	"Tracydisanto",
	"Wade",
};

const char *Multiplayer[15] = {
	"mp_g_m_pros_01",
	"mp_m_exarmy_01",
	"mp_f_deadhooker",
	"mp_f_freemode_01",
	"mp_f_misty_01",
	"mp_f_stripperlite",
	"mp_headtargets",
	"mp_m_claude_01",
	"mp_m_famdd_01",
	"mp_m_fibsec_01",
	"mp_m_freemode_01",
	"mp_m_marston_01",
	"mp_m_niko_01",
	"mp_m_shopkeep_01",
	"mp_s_m_armoured_01",
};
const char *MultiplayerDisplay[15] = {
	"Pros 01",
	"Exarmy 01",
	"Deadhooker",
	"Freemode 01",
	"Misty 01",
	"Stripperlite",
	"Headtargets",
	"Claude 01",
	"Famdd 01",
	"Fibsec 01",
	"Freemode 01",
	"Marston 01",
	"Niko 01",
	"Shopkeep 01",
	"Armoured 01",
};
const char *MainCharacters[3] =
{
	"player_zero",
	"player_one",
	"player_two"
};
const char *MainCharactersDisplay[3] =
{
	"Michael",
	"Franklin",
	"Trevor"
};

const char *ScenarioFemale[23] =
{
	"s_f_m_fembarber",
	"s_f_m_maid_01",
	"s_f_m_shop_high",
	"s_f_m_sweatshop_01",
	"s_f_y_airhostess_01",
	"s_f_y_bartender_01",
	"s_f_y_baywatch_01",
	"s_f_y_cop_01",
	"s_f_y_factory_01",
	"s_f_y_hooker_01",
	"s_f_y_hooker_02",
	"s_f_y_hooker_03",
	"s_f_y_migrant_01",
	"s_f_y_movprem_01",
	"s_f_y_ranger_01",
	"s_f_y_scrubs_01",
	"s_f_y_sheriff_01",
	"s_f_y_shop_low",
	"s_f_y_shop_mid",
	"s_f_y_stripperlite",
	"s_f_y_stripper_01",
	"s_f_y_stripper_02",
	"s_f_y_sweatshop_01",
};
const char *ScenarioFemaleDisplay[23] =
{
	"Fembarber",
	"Maid 01",
	"Shop high",
	"Sweatshop 01",
	"Airhostess 01",
	"Bartender 01",
	"Baywatch 01",
	"Cop 01",
	"Factory 01",
	"Hooker 01",
	"Hooker 02",
	"Hooker 03",
	"Migrant 01",
	"Movprem 01",
	"Ranger 01",
	"Scrubs 01",
	"Sheriff 01",
	"Shop low",
	"Shop mid",
	"Stripperlite",
	"Stripper 01",
	"Stripper 02",
	"Sweatshop 01",
};
const char *ScenarioMale[91] = {
	"s_m_m_ammucountry",
	"s_m_m_armoured_01",
	"s_m_m_armoured_02",
	"s_m_m_autoshop_01",
	"s_m_m_autoshop_02",
	"s_m_m_bouncer_01",
	"s_m_m_chemsec_01",
	"s_m_m_ciasec_01",
	"s_m_m_cntrybar_01",
	"s_m_m_dockwork_01",
	"s_m_m_doctor_01",
	"s_m_m_fiboffice_01",
	"s_m_m_fiboffice_02",
	"s_m_m_gaffer_01",
	"s_m_m_gardener_01",
	"s_m_m_gentransport",
	"s_m_m_hairdress_01",
	"s_m_m_highsec_01",
	"s_m_m_highsec_02",
	"s_m_m_janitor",
	"s_m_m_lathandy_01",
	"s_m_m_lifeinvad_01",
	"s_m_m_linecook",
	"s_m_m_lsmetro_01",
	"s_m_m_mariachi_01",
	"s_m_m_marine_01",
	"s_m_m_marine_02",
	"s_m_m_migrant_01",
	"s_m_m_movalien_01",
	"s_m_m_movprem_01",
	"s_m_m_movspace_01",
	"s_m_m_paramedic_01",
	"s_m_m_pilot_01",
	"s_m_m_pilot_02",
	"s_m_m_postal_01",
	"s_m_m_postal_02",
	"s_m_m_prisguard_01",
	"s_m_m_scientist_01",
	"s_m_m_security_01",
	"s_m_m_snowcop_01",
	"s_m_m_strperf_01",
	"s_m_m_strpreach_01",
	"s_m_m_strvend_01",
	"s_m_m_trucker_01",
	"s_m_m_ups_01",
	"s_m_m_ups_02",
	"s_m_y_airworker",
	"s_m_y_ammucity_01",
	"s_m_y_armymech_01",
	"s_m_y_autopsy_01",
	"s_m_y_barman_01",
	"s_m_y_baywatch_01",
	"s_m_y_blackops_01",
	"s_m_y_blackops_02",
	"s_m_y_busboy_01",
	"s_m_y_chef_01",
	"s_m_y_clown_01",
	"s_m_y_construct_01",
	"s_m_y_construct_02",
	"s_m_y_cop_01",
	"s_m_y_dealer_01",
	"s_m_y_devinsec_01",
	"s_m_y_dockwork_01",
	"s_m_y_doorman_01",
	"s_m_y_dwservice_01",
	"s_m_y_dwservice_02",
	"s_m_y_factory_01",
	"s_m_y_fireman_01",
	"s_m_y_garbage",
	"s_m_y_grip_01",
	"s_m_y_hwaycop_01",
	"s_m_y_marine_01",
	"s_m_y_marine_02",
	"s_m_y_marine_03",
	"s_m_y_mime",
	"s_m_y_pestcont_01",
	"s_m_y_pilot_01",
	"s_m_y_prismuscl_01",
	"s_m_y_prisoner_01",
	"s_m_y_ranger_01",
	"s_m_y_robber_01",
	"s_m_y_sheriff_01",
	"s_m_y_shop_mask",
	"s_m_y_strvend_01",
	"s_m_y_swat_01",
	"s_m_y_uscg_01",
	"s_m_y_valet_01",
	"s_m_y_waiter_01",
	"s_m_y_winclean_01",
	"s_m_y_xmech_01",
	"s_m_y_xmech_02",
};
const char *ScenarioMaleDisplay[91] = {
	"Ammucountry",
	"Armoured 01",
	"Armoured 02",
	"Autoshop 01",
	"Autoshop 02",
	"Bouncer 01",
	"Chemsec 01",
	"Ciasec 01",
	"Cntrybar 01",
	"Dockwork 01",
	"Doctor 01",
	"Fiboffice 01",
	"Fiboffice 02",
	"Gaffer 01",
	"Gardener 01",
	"Gentransport",
	"Hairdress 01",
	"Highsec 01",
	"Highsec 02",
	"Janitor",
	"Lathandy 01",
	"Lifeinvad 01",
	"Linecook",
	"Lsmetro 01",
	"Mariachi 01",
	"Marine 01",
	"Marine 02",
	"Migrant 01",
	"Movalien 01",
	"Movprem 01",
	"Movspace 01",
	"Paramedic 01",
	"Pilot 01",
	"Pilot 02",
	"Postal 01",
	"Postal 02",
	"Prisguard 01",
	"Scientist 01",
	"Security 01",
	"Snowcop 01",
	"Strperf 01",
	"Strpreach 01",
	"Strvend 01",
	"Trucker 01",
	"Ups 01",
	"Ups 02",
	"Airworker",
	"Ammucity 01",
	"Armymech 01",
	"Autopsy 01",
	"Barman 01",
	"Baywatch 01",
	"Blackops 01",
	"Blackops 02",
	"Busboy 01",
	"Chef 01",
	"Clown 01",
	"Construct 01",
	"Construct 02",
	"Cop 01",
	"Dealer 01",
	"Devinsec 01",
	"Dockwork 01",
	"Doorman 01",
	"Dwservice 01",
	"Dwservice 02",
	"Factory 01",
	"Fireman 01",
	"Garbage",
	"Grip 01",
	"Hwaycop 01",
	"Marine 01",
	"Marine 02",
	"Marine 03",
	"Mime",
	"Pestcont 01",
	"Pilot 01",
	"Prismuscl 01",
	"Prisoner 01",
	"Ranger 01",
	"Robber 01",
	"Sheriff 01",
	"Shop mask",
	"Strvend 01",
	"Swat 01",
	"Uscg 01",
	"Valet 01",
	"Waiter 01",
	"Winclean 01",
	"Xmech 01",
	"Xmech 02",
};
const char *StoryScenarioFemale[15] = {
	"u_f_m_corpse_01",
	"u_f_m_miranda",
	"u_f_m_promourn_01",
	"u_f_o_moviestar",
	"u_f_o_prolhost_01",
	"u_f_y_bikerchic",
	"u_f_y_comjane",
	"u_f_y_corpse_01",
	"u_f_y_corpse_02",
	"u_f_y_hotposh_01",
	"u_f_y_jewelass_01",
	"u_f_y_mistress",
	"u_f_y_poppymich",
	"u_f_y_princess",
	"u_f_y_spyactress",

};
const char *StoryScenarioFemaleDisplay[15] = {
	"Corpse 01",
	"Miranda",
	"Promourn 01",
	"Moviestar",
	"Prolhost 01",
	"Bikerchic",
	"Comjane",
	"Corpse 01",
	"Corpse 02",
	"Hotposh 01",
	"Jewelass 01",
	"Mistress",
	"Poppymich",
	"Princess",
	"Spyactress",

};
const char *StoryScenarioMale[45] = {
	"u_m_m_aldinapoli",
	"u_m_m_bankman",
	"u_m_m_bikehire_01",
	"u_m_m_fibarchitect",
	"u_m_m_filmdirector",
	"u_m_m_glenstank_01",
	"u_m_m_griff_01",
	"u_m_m_jesus_01",
	"u_m_m_jewelsec_01",
	"u_m_m_jewelthief",
	"u_m_m_markfost",
	"u_m_m_partytarget",
	"u_m_m_prolsec_01",
	"u_m_m_promourn_01",
	"u_m_m_rivalpap",
	"u_m_m_spyactor",
	"u_m_m_willyfist",
	"u_m_o_finguru_01",
	"u_m_o_taphillbilly",
	"u_m_o_tramp_01",
	"u_m_y_abner",
	"u_m_y_antonb",
	"u_m_y_babyd",
	"u_m_y_baygor",
	"u_m_y_burgerdrug_01",
	"u_m_y_chip",
	"u_m_y_cyclist_01",
	"u_m_y_fibmugger_01",
	"u_m_y_guido_01",
	"u_m_y_gunvend_01",
	"u_m_y_hippie_01",
	"u_m_y_imporage",
	"u_m_y_justin",
	"u_m_y_mani",
	"u_m_y_militarybum",
	"u_m_y_paparazzi",
	"u_m_y_party_01",
	"u_m_y_pogo_01",
	"u_m_y_prisoner_01",
	"u_m_y_proldriver_01",
	"u_m_y_rsranger_01",
	"u_m_y_sbike",
	"u_m_y_staggrm_01",
	"u_m_y_tattoo_01",
	"u_m_y_zombie_01",
};
const char *StoryScenarioMaleDisplay[45] = {
	"Aldinapoli",
	"Bankman",
	"Bikehire 01",
	"Fibarchitect",
	"Filmdirector",
	"Glenstank 01",
	"Griff 01",
	"Jesus 01",
	"Jewelsec 01",
	"Jewelthief",
	"Markfost",
	"Partytarget",
	"Prolsec 01",
	"Promourn 01",
	"Rivalpap",
	"Spyactor",
	"Willyfist",
	"Finguru 01",
	"Taphillbilly",
	"Tramp 01",
	"Abner",
	"Antonb",
	"Babyd",
	"Baygor",
	"Burgerdrug 01",
	"Chip",
	"Cyclist 01",
	"Fibmugger 01",
	"Guido 01",
	"Gunvend 01",
	"Hippie 01",
	"Imporage",
	"Justin",
	"Mani",
	"Militarybum",
	"Paparazzi",
	"Party 01",
	"Pogo 01",
	"Prisoner 01",
	"Proldriver 01",
	"Rsranger 01",
	"Sbike",
	"Staggrm 01",
	"Tattoo 01",
	"Zombie 01",
};